### ISSUE TITLE
TODO for CRS changes

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1244]
to roll out new `sf`, the next things have to be done

* [x] compare reverse dependencies against sf released on rcheckserver docker image
* [x] compare reverse dependencies against sf released on docker image GDAL 3.0.3/PROJ 6.3.0
* [x] check against PROJ 7 release candidates
* [x] submit to CRAN
* [x] write r-spatial blog & sf vignette on WKT2 #1187 #1225 #1234, axis order #1033, transformation pipelines, and datum grids
* [x] inform twitter

**Comment by edzer** [comment]
Twitter: https://twitter.com/edzerpebesma/status/1240239263154921473
R-spatial blog: https://www.r-spatial.org/r/2020/03/17/wkt.html

**Comment by rsbivand** [comment]
And posted on R-sig-geo, link to follow.
