### ISSUE TITLE
s2 related issues

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1771]
A (growing) collection of issues caused by using s2 as geometry engine for ellipsoidal coordinates

- [ ] `st_crop` not working; #1759
- [ ] `Loop 0 is not valid:`; #1762
- [ ] ; Unwanted longitude conversion 0-360 to -180-180 #1751
- [ ] ; problem with Buffer #1749
- [ ] #1748 
- [ ] #1740 
- [ ] #1738 
- [ ] #1692
